### ISSUE TITLE
Exception thrown trying to connect to strange SMB server

### ISSUE THREAD

**Issue by dwendt** [rapid7/ruby_smb#92]
IRC said I should make an issue here. This was run on a network full of weird stuff listening on weird ports. Couldn't tell you what SMB server caused this.

```
[-] x:445      - Auxiliary failed: NoMethodError undefined method `length' for nil:NilClass
[-] x:445      - Call stack:
[-] x:445      -   /usr/local/rvm/gems/ruby-2.4.1/gems/ruby_smb-0.0.14/lib/ruby_smb/dispatcher/socket.rb:56:in `recv_packet'
[-] x:445      -   /usr/local/rvm/gems/ruby-2.4.1/gems/ruby_smb-0.0.14/lib/ruby_smb/client.rb:223:in `send_recv'
[-] x:445      -   /usr/local/rvm/gems/ruby-2.4.1/gems/ruby_smb-0.0.14/lib/ruby_smb/client/negotiation.rb:28:in `negotiate_request'
[-] x:445      -   /usr/local/rvm/gems/ruby-2.4.1/gems/ruby_smb-0.0.14/lib/ruby_smb/client/negotiation.rb:13:in `negotiate'
[-] x:445      -   /usr/local/rvm/gems/ruby-2.4.1/gems/ruby_smb-0.0.14/lib/ruby_smb/client.rb:180:in `login'
[-] x:445      -   /opt/metasploit-framework/lib/metasploit/framework/login_scanner/smb.rb:101:in `attempt_login'
```

https://github.com/rapid7/ruby_smb/blob/master/lib/ruby_smb/dispatcher/socket.rb#L56

Looks like there needs to be a check in case data is nil.

**Comment by dmaloney-r7** [comment]
@dwendt do you have a pcap of this happening? It looks like one of the servers just reset the connection during protocol negotiation. It'd be nice to know why this happened
